# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FAaaJ-O8a4Jp62TL2NxXKy2V6yh6tFS
"""

import pandas as pd

# DataFrame yaratish
data = {
    'Ism': ['muhammadrizo', 'shohruh', 'Jasur', 'Dildora', 'Murod', 'Hasan', 'Shahzod'],
    'Yosh': [19, 19, 21, 23, 25, 21, 24],
    'Kasb': ['Dasturchi', 'Muhandis', 'Doktor', 'qituvchi', 'Iqtisodchi', 'Dasturchi', 'Doktor'],
    'Shahar': ['namanagan', 'namanagan', 'Buxoro', 'Fargona', 'Andijon', 'Toshkent', 'Samarkand']
}

df = pd.DataFrame(data)

# 1. DataFrame ni ko'rish
print("Boshlang'ich DataFrame:")
print(df)